; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
custom_version = 0.0.1
custom_ota_repo = davidvancl/gitlab-pipeline-semaphor
lib_deps =
	bblanchon/ArduinoJson@^7.2.2
	bodmer/TFT_eSPI@^2.5.43
	https://github.com/davidvancl/esp-ota-updater.git#v1.0.1
build_flags =
    -DFW_VERSION=\"${this.custom_version}\"
    -DOTA_REPO=\"${this.custom_ota_repo}\"
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=280
    -DTFT_MOSI=13
    -DTFT_SCLK=14
    -DTFT_CS=12
    -DTFT_DC=4
    -DTFT_RST=5
    -DTFT_BL=2
    -DTFT_BACKLIGHT_ON=HIGH
    -DSPI_FREQUENCY=20000000
    -DSPI_READ_FREQUENCY=6000000
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DLOAD_GFXFF=1
    -DSMOOTH_FONT=1
    -DTFT_INVERSION_ON=1
    -DTFT_RGB_ORDER=TFT_BGR